version: "3.8"

services:
  ahw_tileserver_gl:
    image: maptiler/tileserver-gl:v3.1.1
    container_name: ahw_tileserver_gl
    restart: ${RESTART_POLICY}
    command: --port 3000 --public_url ${PUBLIC_URL}
    ports:
      - 3000
    volumes:
      - ./data:/data
      - ${DATA_TILES_VOLUME}:/data/tiles
      - ${FONTS_VOLUME}:/data/fonts
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true